apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: portal-client-pod
  name: portal-client-pod
  selfLink: /api/v1/namespaces/default/services/portal-client-pod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30703
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: portal-client-pod
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
