apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: memberpod
  name: memberpod
  selfLink: /api/v1/namespaces/default/pods/memberpod
spec:
  containers:
  - image: member:v1
    imagePullPolicy: IfNotPresent
    name: memberpod
    resources: {}
    env:
            - name: enviroment
              value: production
            - name: memberurl
              value: mongodb://member-database:27017/BuildingManagement  
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9cwkf
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-9cwkf
    secret:
      defaultMode: 420
      secretName: default-token-9cwkf
status:
  phase: Pending
  qosClass: BestEffort
